### ISSUE TITLE
Installation issue on Mac M1/arm64 arch

### ISSUE THREAD

**Issue by fgr1986** [ubermag/oommfc#53]
`conda install -c conda-forge oommfc`

Reports (verbose output):

```
collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/r/osx-arm64/current_repodata.json

Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/r/osx-arm64/repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/r/osx-arm64/repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Building graph of deps:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-arm64::__osx==11.1=0:   0%|          | 0/5 [00:00<?, ?it/s]
Examining @/osx-arm64::__archspec==1=arm64:  20%|██        | 1/5 [00:00<00:00, 5607.36it/s]
Examining python=3.9:  40%|████      | 2/5 [00:00<00:00, 7115.02it/s]                      
Examining @/osx-arm64::__unix==0=0:  60%|██████    | 3/5 [00:00<00:00, 409.53it/s]
Examining oommfc:  80%|████████  | 4/5 [00:00<00:00, 541.32it/s]                  
                                                                

Determining conflicts:   0%|          | 0/5 [00:00<?, ?it/s]
Examining conflict for python oommfc:   0%|          | 0/5 [00:00<?, ?it/s]
                                                                           
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/cli/install.py", line 261, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/resolve.py", line 1320, in solve
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError: 
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True
            

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/cli/install.py", line 308, in install
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/cli/install.py", line 295, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/core/solve.py", line 704, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by marijanbeg** [comment]
Hi @fgr1986, thank you for your question. This is a difficult question since we do not have a machine to do the tests ourselves. However, from the error messages, it looks like you did not create an environment with Python 3.8. Could you please make sure you have a clean environment? You can follow this tutorial: https://oommfc.readthedocs.io/en/latest/ipynb/installation-testing-update.html

Please keep us updated.

**Comment by fgr1986** [comment]
Hi @marijanbeg , thanks for your quick responses.
This was in a clean environment, and I tried with both 3.9 and 3.8. 
The installation with pip fails on hp5 libs (will report it).

I will update the tread if I find anything from the log.
Thanks
